# Generated by Django 4.1 on 2023-08-12 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricMeter',
            fields=[
                ('meter_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id счетчика')),
                ('address', models.GenericIPAddressField(verbose_name='ip адрес счетчика')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='порт счетчика')),
            ],
            options={
                'verbose_name': 'Электросчетчик',
                'verbose_name_plural': 'Электросчетчики',
                'ordering': ['-meter_id'],
            },
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('consumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='data_proc.electricmeter')),
            ],
            options={
                'verbose_name': 'Показания счетчика',
                'verbose_name_plural': 'Показания счетчиков',
                'ordering': ['-date'],
            },
        ),
    ]
