# Generated by Django 4.1 on 2023-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_proc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeter',
            name='meter_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='id счетчика'),
        ),
    ]
